-- ---------------------------------------------------------------------------
-- Server-generated user ids.
--
-- The identity sequence starts at 8000, above the seeded demo ids, so an API-provisioned user
-- needs no client-supplied id and cannot collide with a seeded row.
-- ---------------------------------------------------------------------------
alter table app_user alter column id add generated by default as identity (start with 8000);
